theme: jekyll-theme-minimal
title: Louis' homepage
description: I am Inquisitive and curious of the overall functioning of machines. I have a coding interest and great love for the field of engineering with the hope of developing new world-class techniques and innovations affecting society and changing the world as we know it;
